keystore = "/path/to/keystore"

[home]
account = "0x547aff14210b6a72e106e27f34c626762f3c4761"
password = "home_password.txt"
rpc_host = "http://rpc.host.for.home"
rpc_port = 8545
required_confirmations = 0
poll_interval = 5
request_timeout = 60
default_gas_price = 1_000_000_000 # 1 GWEI

[foreign]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
password = "foreign_password.txt"
rpc_host = "https://rpc.host.for.foreign"
rpc_port = 443
required_confirmations = 8
poll_interval = 15
request_timeout = 60
gas_price_oracle_url = "https://gasprice.poa.network"
gas_price_speed = "instant"
gas_price_timeout = 10
default_gas_price = 10_000_000_000 # 10 GWEI

[authorities]
# Keep this section empty

[transactions]
withdraw_relay = { gas = 300000 }
withdraw_confirm = { gas = 300000 }
deposit_relay = { gas = 300000 }
